// Code generated by counterfeiter. DO NOT EDIT.
package servicetesting

import (
	"context"
	"sync"

	"github.com/MarioCarrion/todo-api-microservice-example/internal"
	"github.com/MarioCarrion/todo-api-microservice-example/internal/service"
)

type FakeTaskSearchRepository struct {
	SearchStub        func(context.Context, internal.SearchParams) (internal.SearchResults, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 internal.SearchParams
	}
	searchReturns struct {
		result1 internal.SearchResults
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 internal.SearchResults
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskSearchRepository) Search(arg1 context.Context, arg2 internal.SearchParams) (internal.SearchResults, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 internal.SearchParams
	}{arg1, arg2})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTaskSearchRepository) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeTaskSearchRepository) SearchCalls(stub func(context.Context, internal.SearchParams) (internal.SearchResults, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeTaskSearchRepository) SearchArgsForCall(i int) (context.Context, internal.SearchParams) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskSearchRepository) SearchReturns(result1 internal.SearchResults, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 internal.SearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskSearchRepository) SearchReturnsOnCall(i int, result1 internal.SearchResults, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 internal.SearchResults
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 internal.SearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskSearchRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskSearchRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.TaskSearchRepository = new(FakeTaskSearchRepository)
