// Code generated by counterfeiter. DO NOT EDIT.
package resttesting

import (
	"context"
	"sync"

	"github.com/MarioCarrion/todo-api-microservice-example/internal"
	"github.com/MarioCarrion/todo-api-microservice-example/internal/rest"
)

type FakeTaskService struct {
	ByStub        func(context.Context, internal.SearchParams) (internal.SearchResults, error)
	byMutex       sync.RWMutex
	byArgsForCall []struct {
		arg1 context.Context
		arg2 internal.SearchParams
	}
	byReturns struct {
		result1 internal.SearchResults
		result2 error
	}
	byReturnsOnCall map[int]struct {
		result1 internal.SearchResults
		result2 error
	}
	ByIDStub        func(context.Context, string) (internal.Task, error)
	byIDMutex       sync.RWMutex
	byIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	byIDReturns struct {
		result1 internal.Task
		result2 error
	}
	byIDReturnsOnCall map[int]struct {
		result1 internal.Task
		result2 error
	}
	CreateStub        func(context.Context, internal.CreateParams) (internal.Task, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 internal.CreateParams
	}
	createReturns struct {
		result1 internal.Task
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 internal.Task
		result2 error
	}
	DeleteStub        func(context.Context, string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStub        func(context.Context, string, internal.UpdateParams) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 internal.UpdateParams
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskService) By(arg1 context.Context, arg2 internal.SearchParams) (internal.SearchResults, error) {
	fake.byMutex.Lock()
	ret, specificReturn := fake.byReturnsOnCall[len(fake.byArgsForCall)]
	fake.byArgsForCall = append(fake.byArgsForCall, struct {
		arg1 context.Context
		arg2 internal.SearchParams
	}{arg1, arg2})
	stub := fake.ByStub
	fakeReturns := fake.byReturns
	fake.recordInvocation("By", []interface{}{arg1, arg2})
	fake.byMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTaskService) ByCallCount() int {
	fake.byMutex.RLock()
	defer fake.byMutex.RUnlock()
	return len(fake.byArgsForCall)
}

func (fake *FakeTaskService) ByCalls(stub func(context.Context, internal.SearchParams) (internal.SearchResults, error)) {
	fake.byMutex.Lock()
	defer fake.byMutex.Unlock()
	fake.ByStub = stub
}

func (fake *FakeTaskService) ByArgsForCall(i int) (context.Context, internal.SearchParams) {
	fake.byMutex.RLock()
	defer fake.byMutex.RUnlock()
	argsForCall := fake.byArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskService) ByReturns(result1 internal.SearchResults, result2 error) {
	fake.byMutex.Lock()
	defer fake.byMutex.Unlock()
	fake.ByStub = nil
	fake.byReturns = struct {
		result1 internal.SearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) ByReturnsOnCall(i int, result1 internal.SearchResults, result2 error) {
	fake.byMutex.Lock()
	defer fake.byMutex.Unlock()
	fake.ByStub = nil
	if fake.byReturnsOnCall == nil {
		fake.byReturnsOnCall = make(map[int]struct {
			result1 internal.SearchResults
			result2 error
		})
	}
	fake.byReturnsOnCall[i] = struct {
		result1 internal.SearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) ByID(arg1 context.Context, arg2 string) (internal.Task, error) {
	fake.byIDMutex.Lock()
	ret, specificReturn := fake.byIDReturnsOnCall[len(fake.byIDArgsForCall)]
	fake.byIDArgsForCall = append(fake.byIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ByIDStub
	fakeReturns := fake.byIDReturns
	fake.recordInvocation("ByID", []interface{}{arg1, arg2})
	fake.byIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTaskService) ByIDCallCount() int {
	fake.byIDMutex.RLock()
	defer fake.byIDMutex.RUnlock()
	return len(fake.byIDArgsForCall)
}

func (fake *FakeTaskService) ByIDCalls(stub func(context.Context, string) (internal.Task, error)) {
	fake.byIDMutex.Lock()
	defer fake.byIDMutex.Unlock()
	fake.ByIDStub = stub
}

func (fake *FakeTaskService) ByIDArgsForCall(i int) (context.Context, string) {
	fake.byIDMutex.RLock()
	defer fake.byIDMutex.RUnlock()
	argsForCall := fake.byIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskService) ByIDReturns(result1 internal.Task, result2 error) {
	fake.byIDMutex.Lock()
	defer fake.byIDMutex.Unlock()
	fake.ByIDStub = nil
	fake.byIDReturns = struct {
		result1 internal.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) ByIDReturnsOnCall(i int, result1 internal.Task, result2 error) {
	fake.byIDMutex.Lock()
	defer fake.byIDMutex.Unlock()
	fake.ByIDStub = nil
	if fake.byIDReturnsOnCall == nil {
		fake.byIDReturnsOnCall = make(map[int]struct {
			result1 internal.Task
			result2 error
		})
	}
	fake.byIDReturnsOnCall[i] = struct {
		result1 internal.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) Create(arg1 context.Context, arg2 internal.CreateParams) (internal.Task, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 internal.CreateParams
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTaskService) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeTaskService) CreateCalls(stub func(context.Context, internal.CreateParams) (internal.Task, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeTaskService) CreateArgsForCall(i int) (context.Context, internal.CreateParams) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskService) CreateReturns(result1 internal.Task, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 internal.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) CreateReturnsOnCall(i int, result1 internal.Task, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 internal.Task
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 internal.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskService) Delete(arg1 context.Context, arg2 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskService) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeTaskService) DeleteCalls(stub func(context.Context, string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeTaskService) DeleteArgsForCall(i int) (context.Context, string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTaskService) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskService) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskService) Update(arg1 context.Context, arg2 string, arg3 internal.UpdateParams) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 internal.UpdateParams
	}{arg1, arg2, arg3})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2, arg3})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskService) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeTaskService) UpdateCalls(stub func(context.Context, string, internal.UpdateParams) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeTaskService) UpdateArgsForCall(i int) (context.Context, string, internal.UpdateParams) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTaskService) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskService) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeTaskService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rest.TaskService = new(FakeTaskService)
